
package com.erikthegod.gym.interfaz;

import static com.erikthegod.gym.interfaz.JPPanelEstadisticas.jcbEjercicio;
import com.erikthegod.gym.modelo.Ejercicios;
import com.erikthegod.gym.modelo.Personas;
import com.erikthegod.gym.persistencia.GestorBBDD;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author kinton
 */
public class JPPanelIniciarSesion extends javax.swing.JPanel {

    private JFVentana jfe;
    private GestorBBDD gest = new GestorBBDD();
    private Boolean registrado;
    private ArrayList<Personas> personas = new ArrayList();
    private ArrayList<Ejercicios> ejercicios = new ArrayList();

    public JPPanelIniciarSesion(JFVentana _jfe) {
        initComponents();
        this.jfe = _jfe;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfNombre = new javax.swing.JTextField();
        jtfPass = new javax.swing.JTextField();
        jbIniciaSesion = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jlUser = new javax.swing.JLabel();
        jlUser1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 153));

        jbIniciaSesion.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jbIniciaSesion.setText("Iniciar Sesion");
        jbIniciaSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIniciaSesionActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jButton2.setText("Registrarse");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jlUser.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jlUser.setText("Contraseña");

        jlUser1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jlUser1.setText("Usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jlUser1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jlUser))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfPass, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                            .addComponent(jtfNombre)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jbIniciaSesion)
                        .addGap(31, 31, 31)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbIniciaSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlUser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jtfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)))
                .addGap(129, 129, 129))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbIniciaSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIniciaSesionActionPerformed
        try {
            registrado = gest.comprobarRegistro(jtfNombre.getText(), jtfPass.getText());
            if (registrado == true) {
                if (gest.usuario.getNombre().compareTo("Entrenador") == 0 && gest.usuario.getPass().compareTo("Entrenador") == 0) {
                    personas = gest.recogerPersonas();
                    for (int i = 0; i < personas.size(); i++) {
                        JPPanel.jcbNombre.addItem(personas.get(i).getNombre());
                        JPPanelUsarRutina.jcbPersona.addItem(personas.get(i).getNombre());
                        JPPanelEstadisticas.jcbPersona.addItem(personas.get(i).getNombre());
                    }
                } else {
                    JPPanel.jcbNombre.setVisible(false);
                    JPPanelUsarRutina.jcbPersona.setVisible(false);
                    JPPanelEstadisticas.jcbPersona.setVisible(false);
                    JPPanelUsarRutina.jlUsuario.setText(gest.usuario.getNombre());
                    JPPanel.jlUsuario.setText(gest.usuario.getNombre());
                    JPPanelEstadisticas.jlUsuario.setText(gest.usuario.getNombre());
                }
                this.jfe.cambiaPanel("p1");
            } else {
                JOptionPane.showMessageDialog(null, "Error al iniciar sesion");
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JPPanelIniciarSesion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(JPPanelIniciarSesion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbIniciaSesionActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.jfe.cambiaPanel("p5");
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jbIniciaSesion;
    private javax.swing.JLabel jlUser;
    private javax.swing.JLabel jlUser1;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfPass;
    // End of variables declaration//GEN-END:variables
}
