/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.erikthegod.gym;

import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kinton
 */
public class JPPanelUsarRutina extends javax.swing.JPanel {

    /**
     * Creates new form JPPanelUsarRutina
     */
    Vector vNombres;
    DefaultTableModel dtm;
    double pesoDeseado;
    Personas per = new Personas();
    Ejercicios ejer = new Ejercicios();

    public JPPanelUsarRutina() {
        try {
            initComponents();

            vNombres = new Vector();
            vNombres.add("Categoria");
            vNombres.add("Producto");
            vNombres.add("Precio");
            dtm = new DefaultTableModel(vNombres, 0);
            jtSeries.setModel(dtm);
            initComponents();
            per.recogerPersonas();
            rut.recogerNombreRutina();
            for (int i = 0; i < Rutina.nombresRutinas.size(); i++) {
                jcbRutina.addItem(Rutina.nombresRutinas.get(i).getNombre());
            }
            for (int i = 0; i < Personas.personas.size(); i++) {
                jcbPersona.addItem(Personas.personas.get(i).getNombre());
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JPPanelUsarRutina.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(JPPanelUsarRutina.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    Rutina rut = new Rutina();
    Calculator cal = new Calculator();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbRutina = new javax.swing.JComboBox<>();
        jcbEjercicio = new javax.swing.JComboBox<>();
        jcbPersona = new javax.swing.JComboBox<>();
        jtfSegundos = new javax.swing.JTextField();
        jtfPeso = new javax.swing.JTextField();
        jbCalcular = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtSeries = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jcbRutina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbRutinaActionPerformed(evt);
            }
        });

        jbCalcular.setText("Calcular");
        jbCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCalcularActionPerformed(evt);
            }
        });

        jtSeries.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtSeries);

        jLabel1.setText("Segundos");

        jLabel2.setText("Peso");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbRutina, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbEjercicio, 0, 134, Short.MAX_VALUE)
                            .addComponent(jcbPersona, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(37, 37, 37)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfSegundos, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                                    .addComponent(jtfPeso))
                                .addGap(24, 24, 24))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jbCalcular)
                                .addContainerGap(134, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbRutina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfSegundos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbEjercicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCalcular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCalcularActionPerformed
        try {
            // TODO add your handling code here:
            dtm = new DefaultTableModel(vNombres, 0);
            jtSeries.setModel(dtm);
            rut.recogerEjercicioRutina((String) jcbRutina.getSelectedItem(), (String) jcbEjercicio.getSelectedItem());
            for (int i = 0; i < rut.ejer.getSeries().size(); i++) {
                pesoDeseado = cal.calculoTotal(rut.ejer.getNombre(), jtfSegundos.getText(), jtfPeso.getText(), rut.ejer.getSeries().get(i).rmSerie, (String) jcbPersona.getSelectedItem());
                dtm.setRowCount(dtm.getRowCount() + 1);
                jtSeries.setValueAt(i, i, 0);
                jtSeries.setValueAt(rut.ejer.getSeries().get(i).rmSerie, i, 1);
                jtSeries.setValueAt(pesoDeseado, i, 2);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(JPPanelUsarRutina.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jbCalcularActionPerformed

    private void jcbRutinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbRutinaActionPerformed
        try {
            // TODO add your handling code here:
            ejer.recogerNombreEjerciciosRutina((String) jcbRutina.getSelectedItem());
            for (int i = 0; i < Ejercicios.ejerciciosRutina.size(); i++) {
                jcbEjercicio.addItem(Ejercicios.ejerciciosRutina.get(i).getNombre());
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JPPanelUsarRutina.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(JPPanelUsarRutina.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jcbRutinaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCalcular;
    private javax.swing.JComboBox<String> jcbEjercicio;
    private javax.swing.JComboBox<String> jcbPersona;
    private javax.swing.JComboBox<String> jcbRutina;
    private javax.swing.JTable jtSeries;
    private javax.swing.JTextField jtfPeso;
    private javax.swing.JTextField jtfSegundos;
    // End of variables declaration//GEN-END:variables
}
